### ISSUE TITLE
Invalid caching of top-level files when PWA is enabled

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/Uno.Wasm.Bootstrap#102]
When enabling PWA some top level items (js and .wasm files) get cached incorrectly, leading to inconsistent behavior.

**Comment by nickrandolph** [comment]
@jeromelaban is there a setting in Chrome that we should be changing to prevent this happening? I look at look at some of the PWA settings in Chrome but none of them seem to imply they would adjust this behaviour.

**Comment by jeromelaban** [comment]
Fixed in 1.0.10
