### ISSUE TITLE
InvalidOperationException: The SPA default page middleware...

### ISSUE THREAD

**Issue by AgentFire** [unoplatform/Uno.Wasm.Bootstrap#106]
I have downloaded a [sample](https://github.com/nventive/Uno.GettingStartedTutorial) from your site's [tutorial](https://platform.uno/docs/articles/getting-started-tutorial-1.html), opened it in VS (2019, everything from the "requirements" pages is installed via VS Installer), and when I tried to run a WebAssembly project, I got this in the browser:

```
InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware+<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func<Task> next)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jeromelaban** [comment]
Thanks for trying the bootstrapper! 

Could you take a look at the dist folder to see if the `index.html` file is available there ?

**Comment by AgentFire** [comment]
Well, the file isn't in there, and the folder "dist", along with all its contents, doesn't exist in the solution's zip file, there was an error saying exactly that, so I created the folder, and hence this error.

I'm guessing the build process doesn't create any HTML files, along with the dist folder itself.

**Comment by AgentFire** [comment]
While Ctrl-F5 does start IIS express up, the Build command sometimes just gives me this:

![](https://snipboard.io/DWJu0N.jpg)

**Comment by jeromelaban** [comment]
I'm starting to wonder if there is a problem with path management, or some case sensitivity issues.

Would you mind creating a binlog file by running in a command line `msbuild /r /bl` on the wasm project and send me the resulting file on gitter ? (the `build.binlog` file may contain sensitive information)

**Comment by jeromelaban** [comment]
This is a very unusual problem.

A few things:
- The file in question is not found by an .NET Framework internal method called here: 
https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/b9bfdf254dbbbe0143d62735b250726c8c872171/src/Uno.Wasm.Bootstrap/ShellTask.cs#L618
But it's the `Directory.Delete` method that is doing is own work, and I don't see why it would not find a file it just found to delete.
- Can you try deleting the dist folder completely, and try rebuilding ?
- Could you share your sample project ? (same, through gitter if possible)

Thanks!

**Comment by AgentFire** [comment]
Yes, the error comes and goes, as I've mentioned. After deleting the dist folder and doing a project clean up & rebuild, the Visual Studio did this: "Build failed" (!), with no errors in "Error List" window; just right after that, another Build command **succeeded** without any errors... And there is still not index.html file, and the original Ctrl-F5 Build&Run error in the browser appeared:

```
InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware+<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func<Task> next)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by AgentFire** [comment]
Moved the solution to the root directory, eliminating possible path length issues, and the error kinda disappeared. Closing for now.
