### ISSUE TITLE
[dynamic-runtime] TypeError: cannot pass i64 to or from JS

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/Uno.Wasm.Bootstrap#128]
Running an application using the dynamic runtime fails with the following error:

```
TypeError: cannot pass i64 to or from JS
```

Failure appears when icall is made to:
```csharp
[MethodImpl(MethodImplOptions.InternalCall)]
internal static extern long GetSystemTimeAsFileTime();
```

Opened issue: https://github.com/emscripten-core/emscripten/issues/9562

**Comment by jeromelaban** [comment]
An update is now queued to https://github.com/mono/mono/pull/17816

**Comment by jeromelaban** [comment]
Issue still happens in emscripten 1.39.3; https://github.com/emscripten-core/emscripten/issues/9850

**Comment by jeromelaban** [comment]
Waiting on https://github.com/mono/mono/pull/18016 to update

**Comment by carldebilly** [comment]
![](https://media.giphy.com/media/AEkQtvoWBnFcYh0gCh/giphy.gif)
