### ISSUE TITLE
Documentation outdated or Emscripten 1.38.13 still needed?

### ISSUE THREAD

**Issue by stefan-schweiger** [unoplatform/Uno.Wasm.Bootstrap#129]
In the documentation under pre-requesits you mention

> An active Emscripten 1.38.13 (specifically, until [Esmcripten #7656](https://github.com/emscripten-core/emscripten/pull/7656) gets merged)

But [Esmcripten #7656](https://github.com/emscripten-core/emscripten/pull/7656) was closed as "No longer needed."

Is your documentation outdated or is Emscripten 1.38.13 still needed?

**Comment by jeromelaban** [comment]
The documentation was updated.
