### ISSUE TITLE
Uno.Wasm.Bootstrap.Cli is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by vdiallonort** [unoplatform/Uno.Wasm.Bootstrap#141]
Hello,

If i create a project using .Netcore library i can install Uno.wasm.Bootstratp.cli without any issue but not if I use the netstandard2.0 as describe in the documentation here https://github.com/unoplatform/Uno.Wasm.Bootstrap . The nuget install throw me an error saying Cli is only compatible with netcoreapp2.1. So if I now create a project with net core 2.1 the nuget install of the Cli is working.However it doesn't seem to function with dot net core as when i run F5 Chrome start and close really quickly.

**Comment by jeromelaban** [comment]
Hi @vdiallonort, at this point, the only format supported is the [one defined here](https://github.com/unoplatform/Uno.Wasm.Bootstrap#how-to-use-the-package), with netstandard2.0 as a project head. 

This will change in the future when .NET 5 comes to completion, though.

**Comment by vdiallonort** [comment]
Thanks but when I try to install the Uno.Wasm.Bootstrap.Cli it ask the project to be .Net core and not .Net standard.
<img width="583" alt="DotNet" src="https://user-images.githubusercontent.com/6032994/69082535-9445ab80-0a40-11ea-8804-123f59e424fb.png">
<img width="716" alt="IssueInstall" src="https://user-images.githubusercontent.com/6032994/69082536-94de4200-0a40-11ea-8fe8-a565e2d13972.png">
<img width="771" alt="Bootstrap" src="https://user-images.githubusercontent.com/6032994/69082537-94de4200-0a40-11ea-8f4c-e6497bcd8ab6.png">

**Comment by jeromelaban** [comment]
You cannot install that package, it has to be added manually in the csproj. The UI for this package type is not particularly well exposed by visual studio, unfortunately.

**Comment by vdiallonort** [comment]
Thanks a lot. I will be looking at how to add a nuget package manually. Thanks again for your quick answer.

**Comment by jeromelaban** [comment]
You're welcome. I'll close this issue for now.
