### ISSUE TITLE
Feature request: Make Uno.Wasm.Bootstrap.Cli a .NET CLI tool.

### ISSUE THREAD

**Issue by teo-tsirpanis** [unoplatform/Uno.Wasm.Bootstrap#169]
By that, I mean to be able to install it via `dotnet tool install`.

**Comment by jeromelaban** [comment]
Thanks for the request! 

This project is not a tool, it's a build task. It's cannot be installed, and can only be referenced from nuget. 

What should work, though, is to use `dotnet build` on a project referencing `Uno.Wasm.Bootstrap`. Is this what you're referring to ?

**Comment by teo-tsirpanis** [comment]
> What should work, though, is to use dotnet build on a project referencing Uno.Wasm.Bootstrap. Is this what you're referring to ?

That is a much better option. You have create an MSBuild task and integrate it in the build process.

**Comment by teo-tsirpanis** [comment]
I actually kind of figured out what the tool was supposed to do, and determined that it would be best for it to stay as it is.

I am closing the issue.
