### ISSUE TITLE
Page does not load for debug

### ISSUE THREAD

**Issue by peternary** [unoplatform/Uno.Wasm.Bootstrap#184]
No page is loaded for debug when using version 1.1.0-dev.445.  To test, simply create a default project and update Uno.Wasm.Bootstrap before attempting debug - page does not load.  If you revert to previous version of Uno.Wasm.Debug page loads successfully.

**Comment by DierkDroth** [comment]
@jeromelaban looks like a regression....

**Comment by jeromelaban** [comment]
Make sure to update the Uno.Wasm.Boostrap.Cli package as well, manually in the csproj file.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban

**Comment by peternary** [comment]
That resolves the issue!
