### ISSUE TITLE
The Packager command line in the ShellTask miss some assemblies

### ISSUE THREAD

**Issue by fMichaleczek** [unoplatform/Uno.Wasm.Bootstrap#198]
# Steps to reproduce
- Create a **project X** and add Uno.Wasm.Bootstrap
- Add a _ProjectReference_ to a **project Y** which use the type **XmlDocument** (from the dotnet standard assemblies).

# Expected behavior
- The directory dist\managed **contains** the assembly System.Xml.XmlDocument

# Actual behavior
- The directory dist\managed **doesn't contain** the assembly System.Xml.XmlDocument

# Environment data
- Windows 10 Insiders version 2004 
- Microsoft Visual Studio Community 2019 Preview Version 16.6.0 Preview 2.0
- Uno.Wasm.Bootstrap last git

# My Workaround 

In the method RunPackager from ShellTask.cs, I add the referenced assemblies to solve the problem. 

Before :
```
var packagerResults = RunProcess(packagerBinPath, $"--runtime-config={RuntimeConfiguration} {appDirParm} --zlib {debugOption} {referencePathsParameter} \"{AlignPath(TryConvertLongPath(Path.GetFullPath(Assembly)))}\"", _distPath);
```

After :
```
var _referencedAssembliesPaths = string.Join(" ", _referencedAssemblies.Select(r => $"\"{AlignPath(TryConvertLongPath(Path.GetFullPath(r)))}\" "));

var packagerResults = RunProcess(packagerBinPath, $"--runtime-config={RuntimeConfiguration} {appDirParm} --zlib {debugOption} {referencePathsParameter} {_referencedAssembliesPaths} \"{AlignPath(TryConvertLongPath(Path.GetFullPath(Assembly)))}\" ", _distPath);
```

**Comment by fMichaleczek** [comment]
@jeromelaban i think it's a bug, if i understand the whole chain, i don't want the packager miss some assemblies, I expect to have all after him and use the linker to "clear" them.
It's a complex chain, i don't say i'm right, but i hope you have an opinion about that :-)

**Comment by jeromelaban** [comment]
Thanks for the report!

Reference assemblies cannot be part of the dist layout, as the runtime cannot load them properly (they're empty).

How did you find out this can be an issue ?

**Comment by fMichaleczek** [comment]
oh you right, i make a mistake ... forget my workaround :)

For example, I have "System.Xml.XmlDocument.dll" inside the release/debug directory but not in the dist. I will have a look more in depth, but it's hard to debug :)

If you want to understand the context, i am porting PowerShell to WASM
https://fmichaleczek.github.io/PowerShellLab/

Enter this code : 
```
[AppDomain]::CurrentDomain.GetAssemblies() | Select FullName, Version
Add-Type -AssemblyName Microsoft.PowerShell.ConsoleHost -PassThru
```

It's for make a playground for PowerShell because we have nothing and nobody want to host one :)

**Comment by jeromelaban** [comment]
Just saw your post on twitter! Very cool demo !

As for that assembly, it's actually included in the System.Xml file if I'm not mistaken (all the extensions provided by `System.Xml.XmlDocument`).

Also in the configuration you're using, the dotnet.wasm file only contains native code as the .dll files are interpreted.

**Comment by fMichaleczek** [comment]
thank you so much for your time Jerome.
