### ISSUE TITLE
Using BaseIntermediateOutputPath to derive the emscripten-sdkdir parameter maybe doesn't always work

### ISSUE THREAD

**Issue by thatnerdyguy** [unoplatform/Uno.Wasm.Bootstrap#199]
Running under Windows with WSL.

At least for the small test I did with a new project, BaseIntermediateOutputPath defaulted to "obj\", which would be relative to the project directory. The problem is (I think), when ninja runs, its actually not running with its current directory set to the project directory, but instead to something like workAot.

The following change to my project file fixed it for me. Though I'm guessing there is a better absolute fix that can be made as well:

```xml
<Target Name="FixupEMSDKPath" BeforeTargets="BuildDist">
    <!-- The BuildDist target from the Uno.Wasm.Bootstrap package uses BaseIntermediateOutputPath to 
         help compute the location of the emsdk (to pass to the packager via the emscripten-sdkdir parameter. 
         However, that location needs to be absolute, because ninja runs from a different directory than
         the project path, specifically $(BaseIntermediateOutputPath)Debug\netstandard2.0\workAot (as an example). 
         So we'll make it absolute here to get around that issue -->
    <Message Importance="high" Text="proj path is: $(MSBuildProjectDirectory)"/>
    <Message Importance="high" Text="base intermediate is: $(BaseIntermediateOutputPath)"/>
    <PropertyGroup>
      <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\$(BaseIntermediateOutputPath)</BaseIntermediateOutputPath>
    </PropertyGroup>
    <Message Importance="high" Text="new base intermediate is: $(BaseIntermediateOutputPath)"/>
</Target>
```

without that project change, I would get an error like:

```
1>    Running [\\?\C:\Users\thatnerdyguy\source\repos\TestWASMSkiaDrawing\TestWASMSkiaDrawing\obj\Debug\netstandard2.0\workAot]: C:\WINDOWS\sysnative\bash.exe -c " cd `wslpath \"C:\Users\thatnerdyguy\source\repos\TestWASMSkiaDrawing\TestWASMSkiaDrawing\obj\Debug\netstandard2.0\workAot\"` &&   `wslpath \"ninja\"` "

...

1>    [5/64] obj/emsdk-1.39.11/emsdk/emsdk construct_env emsdk_env.sh
1>    FAILED: emsdk_env.sh
1>    obj/emsdk-1.39.11/emsdk/emsdk construct_env emsdk_env.sh
1>    /bin/sh: 1: obj/emsdk-1.39.11/emsdk/emsdk: not found
```

**Comment by jeromelaban** [comment]
Thanks for the report! 

Interesting issue. Is this always the case or is this caused by a change in the project file? If you use a simple project (like [this one](https://github.com/unoplatform/Uno.Samples/tree/master/UI/SkiaSharpTest/SkiaSharpTest/SkiaSharpTest.Wasm)), does the issue still appear ?

Either way, the packager uses the intermediate path here:

https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/8c826016b29bb0ecf96d9d40afe0827b1760844f/src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets#L129

So passing the full path instead of a relative one would definitely make sense.

**Comment by ZeProgFactory** [comment]
Hi,
I’ve the same issue just using the standard templates out of the box:
`C:\Users\zepro\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): Error : Failed to create directory [\\?\D:\GitWare\Apps\TestUNO\TestUNO\TestUNO.Wasm\bin\Release\netstandard2.0\dist][\\?\D:\GitWare\Apps\TestUNO\TestUNO\TestUNO.Wasm\bin\Release\netstandard2.0\dist]`

**Comment by jeromelaban** [comment]
@ZeProgFactory this looks like a different issue. Which version of the bootstrapper are you using?

**Comment by ZeProgFactory** [comment]
Don't you think that the issue is in the origin of the prefix "\\?\" ?
I tried with Uno.Wasm.Bootstrap 1.0.10 and 1.2.0 .

**Comment by jeromelaban** [comment]
This prefix is required when building using `msbuild`, particularly when running inside of visual studio, but when .NET Core it is not required. 

In which context are you getting this issue? (e.g. running `dotnet build`, running the publish command in Visual Studio)

**Comment by ZeProgFactory** [comment]
I try to publish with VS2019 to my webserver.

**Comment by jeromelaban** [comment]
Thanks. This is an issue that I thought was fixed, but clearly is not. You can add the following line in your csproj to work around it:

```xml
<WasmShellEnableLongPathSupport>false</WasmShellEnableLongPathSupport>
```

in the first `<PropertyGroup>` of your webassembly project.

**Comment by ZeProgFactory** [comment]
Thank you, that solvers that problem :-) 
Now I’ve to search why the program only works from VisualStudio …

**Comment by ChM40** [comment]
Hi trying to publish in my local IIS a UnoTest Project, just generated in Visual studio 2019 (Only "Hello, world!"). 
Added <WasmShellEnableLongPathSupport>false</WasmShellEnableLongPathSupport> solved the publish problem. 
But when I want launch my app from localhost:xxxxx Error 500.19 with Code 0x8007000d.
When I launch the wsam in debug ou release mode from VS2019 in IIS Express with Edge or Canary there is no problem it done what it do.
Is there a known issue or particular config to solved this problem?

**Comment by ChM40** [comment]
I tried a publish with a FolderProfile and copy the content in my site folder same issue HTTP 500.19 with Code 0x8007000d.

**Comment by jeromelaban** [comment]
If you want to publish to a local or custom IIS, you'll need to enable the rewrite module: https://www.iis.net/downloads/microsoft/url-rewrite

**Comment by ChM40** [comment]
Thank you,  I've found this same issue by analyzing the web.config file right now.
 
But I encountered another problem to launch the app as I solved it by adding in web.config generated this line : 
<remove fileExtension=".json" /> 
before : 
 
      <mimeMap fileExtension=".json" mimeType="application/octet-stream" />

Now I can publish under IIS on local machine and on my webserver.

**Comment by jeromelaban** [comment]
Interesting finding! I'll try adding it to to the default, there's most probably no harm removing it if it does not exist.

Thanks!

**Comment by mattleibow** [comment]
@jeromelaban I am also getting this issue on my project...

My csproj:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>SkiaSharp.Tests</RootNamespace>
    <AssemblyName>SkiaSharp.Tests</AssemblyName>
    <WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>
    <SkipGenerateAssemblyVersionInfo>true</SkipGenerateAssemblyVersionInfo>
    <SkipMDocGenerateDocs>true</SkipMDocGenerateDocs>
    <SkipCopyToOutputDirectory>true</SkipCopyToOutputDirectory>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="@(SkiaSharpStaticLibrary)" />
    <WasmShellExtraEmccFlags Include="-s ASSERTIONS=1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="2.80.0-pr.1389.8" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.3.0-dev.44" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.3.0-dev.44" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.extensibility.core" Version="2.4.1" />
    <PackageReference Include="xunit.runner.utility" Version="2.4.1" />
  </ItemGroup>
</Project>
```

**Comment by jeromelaban** [comment]
@mattleibow that last issue is actually an emscripten issue, the emsdk is broken. It's possible to pin the emsdk, like this: https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/c6d354c639ec47ddf01480ff9dee79362e04752a/src/Uno.Wasm.Bootstrap/build/scripts/emscripten-setup.sh#L30

**Comment by mattleibow** [comment]
Ah, yeah. I recall that I _just_ patched my CI which was downloading a bad emscripten. 🤦 

Thanks for pointing that out to me lol.
