### ISSUE TITLE
wsl path problem

### ISSUE THREAD

**Issue by meee1** [unoplatform/Uno.Wasm.Bootstrap#201]
from windows VS 2019 16.6 p4

`26>Downloading mono-wasm-34cccfa2fde to C:\Users\michael\AppData\Local\Temp\mono-wasm-34cccfa2fde.aot.zip
26>C:\Users\michael\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.29\build\Uno.Wasm.Bootstrap.targets(124,5): error : ninja: error: '/mnt/c/Program', needed by 'linker-in/Microsoft.AspNetCore.WebUtilities.dll', missing and no known rule to make it
26>C:\Users\michael\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.29\build\Uno.Wasm.Bootstrap.targets(124,5): error : System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
26>C:\Users\michael\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.29\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8c826016b29bb0ecf96d9d40afe0827b1760844f.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 604
26>C:\Users\michael\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.29\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v8c826016b29bb0ecf96d9d40afe0827b1760844f.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 166`

from build.ninja

`build $appdir/$deploy_prefix/Blazor.Extensions.Storage.dll: cpifdiff $builddir/linker-out/Blazor.Extensions.Storage.dll
build $builddir/linker-in/Microsoft.AspNetCore.WebUtilities.dll: cp /mnt/c/Program Files/dotnet/sdk/NuGetFallbackFolder/microsoft.aspnetcore.webutilities/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.WebUtilities.dll
build $appdir/$deploy_prefix/Microsoft.AspNetCore.WebUtilities.dll: cpifdiff $builddir/linker-out/Microsoft.AspNetCore.WebUtilities.dll
build $builddir/linker-in/Microsoft.Net.Http.Headers.dll: cp /mnt/c/Program Files/dotnet/sdk/NuGetFallbackFolder/microsoft.net.http.headers/2.2.0/lib/netstandard2.0/Microsoft.Net.Http.Headers.dll
build $appdir/$deploy_prefix/Microsoft.Net.Http.Headers.dll: cpifdiff $builddir/linker-out/Microsoft.Net.Http.Headers.dll
build $builddir/linker-in/Microsoft.AspNetCore.Blazor.HttpClient.dll: cp /mnt/c/Users/michael/.nuget/packages/microsoft.aspnetcore.blazor.httpclient/3.2.0-preview3.20168.3/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.HttpClient.dll`

**Comment by jeromelaban** [comment]
Thanks for the report! 

Aside from the fact that quoting is missing, I'm curious why you're ending up including `Microsoft.AspNetCore.WebUtilities.dll`, as it's part of .NET Core, and .NET core is not yet supported by mono (and by extension the bootstrapper).

What are you trying to achieve ?

**Comment by jeromelaban** [comment]
Recent updates may have fixed this issue.
