### ISSUE TITLE
Build error on Linux with FullAOT enabled

### ISSUE THREAD

**Issue by maierfelix** [unoplatform/Uno.Wasm.Bootstrap#217]
I can't build with FullAOT enabled, but in Interpreter mode everything builds and runs fine. I'm on WSL Ubuntu 18.04.

When trying to build in AOT mode, I'm getting:
````
/home/user/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.16/build/Uno.Wasm.Bootstrap.targets(124,5): error : ninja: error: build.ninja:1: bad $-escape (literal $ must be written as $$) [/home/user/csharp/HelloWasm.csproj]
/home/user/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.16/build/Uno.Wasm.Bootstrap.targets(124,5): error : mono_sdkdir = \\wsl$\Ubuntu-18.04\tmp\mono-wasm-1add5cbc06a [/home/user/csharp/HelloWasm.csproj]
/home/user/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.16/build/Uno.Wasm.Bootstrap.targets(124,5): error :                    ^ near here [/home/user/csharp/HelloWasm.csproj]
/home/user/.nuget/packages/uno.wasm.bootstrap/1.2.0-dev.16/build/Uno.Wasm.Bootstrap.targets(124,5): error : System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch) [/home/user/csharp/HelloWasm.csproj]
````

I'm on Emscripten 1.39.9 and Mono 5.16.0. I also switched both to latest versions, results in same error.

This is my csproj file:
````xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <WasmShellMonoRuntimeExecutionMode>FullAOT</WasmShellMonoRuntimeExecutionMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.2.0-dev.1" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.2.0-dev.1" PrivateAssets="all" />
 </ItemGroup>

</Project>
````

**Comment by jeromelaban** [comment]
Thanks for the report!

Which version of Windows are you running ? (Running `winver.exe` will tell you).

**Comment by jeromelaban** [comment]
Also, what command are you running and in which environment (e,g, directly in WSL or from VS) ?

**Comment by maierfelix** [comment]
Windows 10 Version 1909 (OS Build 18363.657). I use WSL Ubuntu 18.04.

**Comment by jeromelaban** [comment]
Indeed, Interpreter speed is not appropriate. The reason I'm asking is there's `\\wsl$\` in your path, and I'm wondering if this is related to the fact that you're building directly from the filesystem exposed through the windows explorer.

Are you building from visual studio ? If you are, where is the project located?  The bootstrapper can from directly from WSL (from the shell) or from a local windows path (e.g. C:\ based).

**Comment by maierfelix** [comment]
I don't build from Visual Studio, also I don't see `\\wsl$\` in my path. The project is located in `/mnt/c/Users/User/Desktop/LXSS_SHARED/test`. I tried moving it to `/home`, didn't help either

**Comment by maierfelix** [comment]
I just directly use mono-wasm now, closing this..
