### ISSUE TITLE
Cannot build AOT on mac/linux

### ISSUE THREAD

**Issue by mijay** [unoplatform/Uno.Wasm.Bootstrap#234]
When building with .NET Core on Mac I get the following error:
```
Cannot open assembly 'ninja': No such file or directory.
packages/uno.wasm.bootstrap/1.3.0-dev.18/build/Uno.Wasm.Bootstrap.targets(125,5): error : System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
packages/uno.wasm.bootstrap/1.3.0-dev.18/build/Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_vff98e76be0ab452db3d9cfd3ddaf96e427d09be5.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 684
packages/uno.wasm.bootstrap/1.3.0-dev.18/build/Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_vff98e76be0ab452db3d9cfd3ddaf96e427d09be5.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 175
```

I suspect this is caused by [`RunProcess("ninja")`](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.Bootstrap/ShellTask.cs#L645) line, since that executes `mono ninja` when on .NET Core, while on WSL it runs just `ninja` since [it doesn't end with `.exe`](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.Bootstrap/ShellTask.cs#L422).

**Comment by jeromelaban** [comment]
Thanks for the report! 

On macOS, you'll need to run this setup script: `packages/uno.wasm.bootstrap/1.3.0-dev.18/scripts/dotnet-setup.sh`, and have an active emscripten 1.39.11 setup in the environment. This is not well documented yet.

Note that if you're trying to build on mac, AOT is not yet supported. It's only possible to build with `.a` files at this time as mono does not yet provide the macOS toolchain binaries for AOT.

**Comment by mijay** [comment]
No problem, you have a grate project! And documentation can always follow 😉 

I do not think that emscripten is a problem. If I do not configure it, the build fails earlier.

Actually, I was able to reproduce exactly the same error on ` unoplatform/wasm-build` docker image. So I do not think it is mac-specific - it is basically any non-windows environment.

**Comment by jeromelaban** [comment]
Thanks!

This is curious, as the CI for this repo is running on [linux using this image](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=16521&view=logs&j=4cebab3a-088f-50a9-cb69-d6e148196da1). Are you able to run ninja in the same shell your are running the command in ?

**Comment by mijay** [comment]
Yes, I am. I also think I see the difference: CI [uses](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/master/.vsts-ci-linux.yml#L76) mono's msbuild, while i use `dotnet build`, because of the need for .netstandard 2.1.

That seems to result in different codepaths in [`RunProcess`](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/master/src/Uno.Wasm.Bootstrap/ShellTask.cs#L435).

**Comment by jeromelaban** [comment]
This should be fixed in latest dev builds.
