### ISSUE TITLE
AOT Compilation Error - SignalR

### ISSUE THREAD

**Issue by SirKlosterIII** [unoplatform/Uno.Wasm.Bootstrap#276]
I have the following error trying to compile in FullAOT mode with the nugget **Microsoft.AspNetCore.SignalR.Client**

System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)

Linker:
`
<linker>
  <assembly fullname="unowasmtest">
    <namespace fullname="unowasmtest" />
  </assembly>
  <assembly fullname="Microsoft.AspNetCore.SignalR.Client ">
    <namespace fullname="Microsoft.AspNetCore.SignalR.Client" />
  </assembly>
  <assembly fullname="Microsoft.AspNetCore.Http.Connections.Client"/>
  <assembly fullname="Microsoft.Extensions.Options"/>
  <assembly fullname="Microsoft.Extensions.Logging"/>
  <assembly fullname="Microsoft.AspNetCore.SignalR.Client.Core"/>
  <assembly fullname="Microsoft.AspNetCore.SignalR.Protocols.Json"/>
  <assembly fullname="Microsoft.AspNetCore.Http.Connections.Common"/>
  <assembly fullname="Microsoft.Extensions.Logging.Abstractions"/>
  <assembly fullname="Microsoft.AspNetCore.SignalR.Common"/>
  <assembly fullname="Microsoft.Bcl.AsyncInterfaces"/>
  <assembly fullname="Microsoft.Extensions.DependencyInjection"/>
  <assembly fullname="System.Threading.Channels"/>
</linker>`

**Comment by jeromelaban** [comment]
This should be fixed in latest dev using net5.0 TargetFramework.
