### ISSUE TITLE
calling functions from embedded, 3rd party JavaScript libraries returns "ReferenceError: function is not defined"

### ISSUE THREAD

**Issue by baskren** [unoplatform/Uno.Wasm.Bootstrap#320]
## Current behavior

I am hoping this is a "you're doing it wrong" problem and not a bug.  Also, please redirect me if this is not a Bootstrap issue.

I followed [these](https://platform.uno/docs/articles/interop/wasm-javascript-1.html#invoke-javascript-code-from-c) instructions and was able to successfully call simple JavaScript functions that were stored in an EmbeddedResource.

Next, I tried following [these](https://github.com/unoplatform/Uno.Wasm.Bootstrap#support-for-additional-js-files) instructions using the [html2canvas](https://html2canvas.hertzen.com/) and [mobile-detect](https://github.com/hgoebl/mobile-detect.js) JavaScript libraries, but it would not work.

### Additional Observations:

1. The libraries are into the JavaScript sources:
     ![image](https://user-images.githubusercontent.com/2528888/102641166-9f7a7780-4129-11eb-884d-71b6d5f67ca5.png)
2. `resolve.js` appears to be processing these libraries during bootstraping:
```
Done loading the BCL
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/WasmWebSockets)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/jquery-pep)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/setImmediate)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/Uno.UI)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/html2canvas.min)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/LibTest)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/mobile-detect)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/UnoUtils)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/AppManifest)
uno-bootstrap.js:438 Loading dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/TextToSpeech_GetVoices)
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/AppManifest) - remains 9 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/setImmediate) - remains 8 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/Uno.UI) - remains 7 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/LibTest) - remains 6 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/UnoUtils) - remains 5 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/mobile-detect) - remains 4 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/WasmWebSockets) - remains 3 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/TextToSpeech_GetVoices) - remains 2 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/jquery-pep) - remains 1 other(s).
uno-bootstrap.js:431 Loaded dependency (./package_208ec4e18fef024975412215d52727b3d243a5ec/html2canvas.min) - remains 0 other(s).

```
3.  Simple JavaScript functions that I created and stored in an EmbeddedResource are available in the JavaScript Console:
```javascript
> console.log(libTest)
 ƒ libTest() {
    return 'IT WORKS!';
}
< undefined
```
4. functions from the Embedded JavaScript libraries do not appear to be available in the JavaScript Console:
```javascript
> console.log(html2canvas)
 Uncaught ReferenceError: html2canvas is not defined
    at <anonymous>:1:13
```

## Expected behavior

functions from 3rd party embedded JavaScript libraries are available.

## How to reproduce it (as minimally and precisely as possible)

1. Build / Run the below VisualStudio Solution, targeting the `WasmTricks.Wasm` project
    https://github.com/baskren/Uno.JavascriptReferenceNotFound
2. In the browser, tap the [html2canvas] button.  If successful, the `Hello, world!` text should be replaced with `alright!`.  Rather, the `Hello, world!` text is replaced with the JavaScript error: `ReferenceError: html2canvas is not defined`.

## Workaround

none known

## Environment

Nuget Package Version(s):

- Uno.Wasm.Bootstrap (1.3.4 and 1.3.6)
- Uno.Wasm.Bootstrap.DevServer (1.3.4 and 1.3.6)
- Uno.Ui (3.2.0 and 3.3.0)
- Uno.Core (2.1.0)

IDE:

- [ ] Visual Studio 2017 (version: )
- [ x ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment]
Thanks for the report!

It's likely that the html2canvas is enabling `require.js` support and that the dependency is loaded in a different context. 

Try using the non-minified version of the library and place a breakpoint at the beginning of that file to see what's being created and where.

**Comment by baskren** [comment]
@jeromelaban 

Thank you for the quick response.  I replaced the `html2canvas` with the unminimized version and put a **first breakpoint** at the beginning of it:

```javascript
/*!
 * html2canvas 1.0.0-rc.7 <https://html2canvas.hertzen.com>
 * Copyright (c) 2020 Niklas von Hertzen <https://hertzen.com>
 * Released under MIT License
 */
(function (global, factory) {                                                     // <<< BREAKPOINT  HERE >>>
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    (global = global || self, global.html2canvas = factory());
}(this, function () { 'use strict';

...
```
Likewise, I put a **second breakpoint** on the line (in JavaScript) where I call `html2canvas`:
```javascript
function libTest2() {
    html2canvas(document.body).then(console.log('alright!'));                     // <<< BREAKPOINT HERE >>>
    return 'completed_libTest2';
}
```

Additionally, I put a watch on `this` so I could determine the context.  

When I reloaded the page, the first breakpoint was triggered and `this: window` in the watch.

When I tapped on the [html2canvas] button (which ultimately invoked the `libTest2()` function, above), the second breakpoint was triggered.  Again, `this: window` was in the watch.

That would be as I expected.

However, at line 6949 of `html2canvas`:

```javascript
6947    var _this = undefined;
6948    var parseColor$1 = function (value) { return color.parse(Parser.create(value).parseComponentValue()); };
6949    var html2canvas = function (element, options) {    /// <<< BREAKPOINT HERE >>>
6950        if (options === void 0) { options = {}; }
6951        return renderElement(element, options);
6952    };
```
 `this: undefined` was in the watch.

Likewise,  `this: undefined` was in the watch at line 7081:

```javascript
7080
7081    return html2canvas;
7082
7083 }));
```

Which, when I stepped over, popped out at `require.js`, where `this: Object` was in the watch.

Again, I may be misinterpreting this but this appears to validate your assertion that `require.js` is loading this function in the wrong context.  Now I'm out of my depth.   Would you have a suggestion?

**Comment by jeromelaban** [comment]
Thanks for the update!

I've created https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/321 to update the documentation for this specific scenario.

**Comment by baskren** [comment]
Rock on!  Thanks!
