### ISSUE TITLE
The File "dotnet-runtime-wasm-XX-XX-Release.zip" is Needlessly Downloaded on Each Build

### ISSUE THREAD

**Issue by Acmion** [unoplatform/Uno.Wasm.Bootstrap#322]
**Issue**
When building a project that is set up in accordance with the instructions of Uno.Wasm.Bootstrap, the file `dotnet-runtime-wasm-XX-XX-Release.zip` is needlessly downloaded on each build. 

Everytime after clicking on build the following message appears in the console:
```
Downloading dotnet-runtime-wasm-7043528-21442-Release to C:\Users\Acmion\AppData\Local\Temp\dotnet-runtime-wasm-7043528-21442-Release.zip
```

This can also be confirmed from the files last modified time, which is always updated to the time of the newest build.

**Expected Outcome**
Don't download the file if it already exists.

**Reproducing Repository**
[https://github.com/Acmion/UnoWasmBootstrapDownloadBug](https://github.com/Acmion/UnoWasmBootstrapDownloadBug)

**Temporary Fix**
To temporarily fix this problem one can first download (or copy from its AppData path) `dotnet-runtime-wasm-XX-XX-Release.zip` and place it in directory called `Assets` directly under the project root (same directory in which the `.csproj` file exists) and then update the `.csproj` file accordingly:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <MonoRuntimeDebuggerEnabled Condition="'$(Configuration)'=='Debug'">true</MonoRuntimeDebuggerEnabled>
        
        <!-- Bug fix start. Note: "$(MSBuildProjectDirectory)" is a relative path. -->
        <NetCoreWasmSDKUri>$(MSBuildProjectDirectory)/Assets/dotnet-runtime-wasm-7043528-21442-Release.zip</NetCoreWasmSDKUri>
        <!-- Bug fix end. -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.0.0-dev.69" />
        <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.0.0-dev.69" PrivateAssets="all" />
    </ItemGroup>
</Project>
```

**Other**
Big thanks for an actually understandable way of compiling C# to AOT WASM!

**Comment by jeromelaban** [comment]
@Acmion Thanks for the report. We've made some changes around downloads recently. Would you know if this still happens ?
