### ISSUE TITLE
The build time is too long. Is there a good way to shorten the build time?

### ISSUE THREAD

**Issue by Daoting** [unoplatform/Uno.Wasm.Bootstrap#326]
When using interpretation mode and static link e_sqlite3.bc, the build process takes 26 minutes and other modes are slower. Is there a way to avoid static linking at e_sqlite3.bc with each build?

**Comment by jeromelaban** [comment]
Thanks for the report. 26 minutes is extremely long for a build... are you using WSL 2 by any chance ? This may be the cause of the issue.

Can you try following [the steps here](https://github.com/unoplatform/Uno.Wasm.Bootstrap#serve-the-wasm-app-through-windows-linux-subsystem) and see if this improves ?

**Comment by Daoting** [comment]
Yes, it takes only 3 minutes to adjust to WSL1 build, thanks! Because of this [info,](https://github.com/unoplatform/Uno.Wasm.Bootstrap#required-configuration-for-aot-mixed-mode-or-external-bitcode-support-compilation-on-windows-10) I thought the higher the version, the better.
