### ISSUE TITLE
Wrong path detection for bash.exe on WSL2 when executing compiling a project using FullAOT mode 

### ISSUE THREAD

**Issue by jijiechen** [unoplatform/Uno.Wasm.Bootstrap#329]
On Windows 10 version 2004 (OS Build 19041.685) with WSL2 enabled and Ubuntu 20 installed, I tried to compile a simple project using Uno.Wasm.Bootstrap.

I got the error message prompt

```
The Windows Subsystem for Linux is not installed, please install Ubuntu 18.04 by visiting...
```

I tried to find where the bash.exe locates on my PC using where.exe, and the result is `C:\Windows\System32\bash.exe`.
So I think the hard coded path detection at `ShellTask.cs` is incorrect in some scenarios.

After I corrected the paths and rebuilt the `Uno.Wasm.Bootstrap`, the build proceed successfully.

**Comment by jeromelaban** [comment]
Thanks for the report. How are you building your application? Through the command line or Visual Studio 2019 ?

**Comment by jijiechen** [comment]
@jeromelaban 
Thanks for the reply. 
I used the Rider IDE to build the project. I suppose it behaviors the same as Visual Studio. It invokes MSBuild tasks to complete the building.

**Comment by jeromelaban** [comment]
Got it. The reason for the path to be using `sysnative` is because msbuild runs using 32 bits by default in most environments, but it may be that Rider behaves differently and uses 64 bits by default.

Can you validate that building using `dotnet build` at the command line does not be causing this issue ?

**Comment by jijiechen** [comment]
Hi, I've just tried both `dotnet build` and `dotnet msbuild`, the same error prompted.
The path `C:\Windows\sysnative` indeed does not exist on my PC. 

Here are the versions:
```bash
$ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

$ wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         1
  docker-desktop         Running         2
  CentOS7                Running         2
  docker-desktop-data    Running         2

$ dotnet --version
5.0.101

$ dotnet --list-sdks
3.1.302 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
```

**Comment by jeromelaban** [comment]
The path sysnative is not an actual path, but is supposed to be automatically redirected when running in 32-bits processes. It could be that your machine somehow prefers 64-bits processes. I'll make adjustments to check for the path.

**Comment by jijiechen** [comment]
Thank you for the effort.
