### ISSUE TITLE
Error: The Microsoft.JSInterop.js library is not loaded.

### ISSUE THREAD

**Issue by legistek** [unoplatform/Uno.Wasm.Bootstrap#355]
The bootstrapper is working fine for pure C# but I'm trying to do barebones JS interop and keep getting the error message "The Microsoft.JSInterop.js library is not loaded.".

I'm using this code to do interop, hoping to do it directly without reliance on any third party packages:

```
namespace WebAssembly.JSInterop
{
    internal static class InternalCalls
    {
        // The exact namespace, type, and method names must match the corresponding entries
        // in driver.c in the Mono distribution

        // We're passing asyncHandle by ref not because we want it to be writable, but so it gets
        // passed as a pointer (4 bytes). We can pass 4-byte values, but not 8-byte ones.
        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern string InvokeJSMarshalled(out string exception, ref long asyncHandle, string functionIdentifier, string argsJson);

        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern TRes InvokeJSUnmarshalled<T0, T1, T2, TRes>(out string exception, string functionIdentifier, T0 arg0, T1 arg1, T2 arg2);
    }
}
```

Either call results in that message.

**Comment by jeromelaban** [comment]
Thanks for the report.

Those two APIs cannot be used in the bootstrapper directly, they need to be backed by another piece of javascript that is not present in the bootstrapper. You can use this instead: https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/main/src/Uno.Wasm.Tests.Shared/Runtime.cs

**Comment by legistek** [comment]
Brilliant! I figured as much but I couldn't for the life of me find the alternative. Thank you sir. Works perfectly.

**Comment by legistek** [comment]
Sorry one quick follow up  -
If I want to exchange structured data between C# and JS (assume I'm using `LayoutKind.Explicit` etc and getting the data inside my JS function using Module.HEAPxxx) would the best way be to just pass in the pointer to the object as part of the string parameter to `InvokeJS`?

```
            unsafe
            {
                var addr = &myObject;
                Runtime.InvokeJS($"window.myFunc({(IntPtr)addr})");
            }
```

When I was using the Blazor WASM bootstrapper previously I was using `InvokeUnmarshalled`.

I'm just looking for the absolute lowest-level option (think C++ and inline assembly) to try to push efficiency to the absolute max. Embedding the pointer in the Javascript code being passed to `InvokeJS` feels like it wouldn't be as efficient as `InvokeUnmarshalled` but I really have no way to know for sure.

Thanks again!
