### ISSUE TITLE
64-bit bash.exe path is still wrong

### ISSUE THREAD

**Issue by blattersturm** [unoplatform/Uno.Wasm.Bootstrap#377]
https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/8b84df5ba8e88a0d597f7cc751b9c8a91cb8b16a/src/Uno.Wasm.Bootstrap/ShellTask.cs#L526-L529

sysnative maps to system32 in WOW64 processes, however you're assuming there's a C:\Windows\bash.exe. WSL installs this in C:\Windows\system32\, so this code should rather check for WINDIR + system32\\bash.exe.

**Comment by jeromelaban** [comment]
Thanks for the update! I have not found a way to validate this locally yet, so this was bound to happen.

https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/380 may help.

**Comment by blattersturm** [comment]
This seems to happen when directly using dotnet CLI build flow if the installed SDK on the host is 64 bits, since `dotnet build` will chain into 64-bit MSBuild too.

In VS, you of course get 32-bit everything since VS is mostly x86.
