### ISSUE TITLE
`Microsoft.Windows.Compatibility` hard-locked on version `5.0.0`

### ISSUE THREAD

**Issue by mmarinchenko** [unoplatform/Uno.Wasm.Bootstrap#423]
`Microsoft.Windows.Compatibility` reference in [Uno.Wasm.Bootstrap.targets#L90](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/73a338c9a1f67a15b18700df37035eb9d065c04c/src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets#L90) makes it impossible to change the package version at the project level.

It seems you're [spending time](https://github.com/search?q=org%3Aunoplatform+Microsoft.Windows.Compatibility&type=issues) to bump its version in sample projects but this doesn't lead to any actual effect.

Should it really be there? And if so, should it be at least `5.0.*` instead of `5.0.0`?

**Comment by jeromelaban** [comment]
Thanks for the report. It's actually having an effect, but likely only on CI, because the bootstrap target is not restoring the content provided by the targets file as it's included after the `restore` target.

I'll remove this from the bootstrapper targets file.

**Comment by mmarinchenko** [comment]
It looks like this should have been closed along with PR #495 (9e15eb0).

**Comment by jeromelaban** [comment]
It's been kept open because the explicit packages are still in place. We're likely going to change the behavior for projects targeting net7 and up explicitly, and close this issue along with it.

**Comment by mmarinchenko** [comment]
@jeromelaban thanks for the explanation!👍

**Comment by jeromelaban** [comment]
This is fixed in latest 7.0-dev bits.
