### ISSUE TITLE
Combine it with custom Mono.js and Mono.wasm ?

### ISSUE THREAD

**Issue by roozbehid** [unoplatform/Uno.Wasm.Bootstrap#51]
I am working on a similar nuget that enables Winforms but as of now I need to use my own mono.wasm and mono.js becuase I have additional static libraries linked to them.
This way I can no more bother with having build targets and etc. and just use your nuget

**Comment by jeromelaban** [comment]
That's a nice project of yours :)

That's definitely doeable. For now we're just copying the content of the mono sdk folder, but an additional step can be added to allow for customization. Is it the only customizations you need ?

**Comment by roozbehid** [comment]
Thanks.

Well I am also changing some of those facade dlls with my version too. So maybe also that too :D

**Comment by jeromelaban** [comment]
Then in this context, if you want to experiment, the bootstrapper already provides a way to use an arbitrary SDK, by means of [these properties](https://github.com/nventive/Uno.Wasm.Bootstrap#updating-the-mono-sdk-build). The only requirement is that the file should be named `mono-wasm-XXXX.zip`, but you can use a local or nuget provided path, [like this](https://github.com/nventive/Uno.Wasm.MonoRuntime/blob/d07492fa86195c88d46d3d3654305d9c8985cb34/src/Uno.Wasm.MonoRuntime/build/netstandard1.0/Uno.Wasm.MonoRuntime.props#L9).

**Comment by jeromelaban** [comment]
Custom mono.js is not supported, but additional javascrip,  .bc and .a files are now supported.
