### ISSUE TITLE
Linker Strips all classes when overrideing a runtime assembly.

### ISSUE THREAD

**Issue by groogiam** [unoplatform/Uno.Wasm.Bootstrap#568]
There appears to be a bug in where the liner strips everything out of the output assemblies when attempting to override an runtime assembly. 

I'm trying to reference a custom version of System.Net.Quic to work around this issue https://github.com/dotnet/runtime/issues/76420

When doing this the IL Linker seems to strip everything from every assembly even though they are ignored in the LinkerConfig.xml

![image](https://user-images.githubusercontent.com/1992395/193604032-547b7f23-74be-4eec-a8c2-eabfc3f3ff4a.png)

**Comment by jeromelaban** [comment]
Thanks for the report. This is likely a scenario that is not supported currently, but if you can provide a sample project, it will help.

**Comment by groogiam** [comment]
Repro attached. Thanks.

[Uno568Repro.zip](https://github.com/unoplatform/Uno.Wasm.Bootstrap/files/9698557/Uno568Repro.zip)

**Comment by groogiam** [comment]
It looks like the 7.x target .NET 7 which will require retargeting the rest of my application. 

Does this functionality work in 3.3.x? https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/main/doc/features-nuget-package-overrides.md 

If so can I create an nuget package with the updated System.Net.Quic functionality and just favor that implementation using WasmShellRuntimeCopyExclude?

**Comment by jeromelaban** [comment]
Updating 7.x won't need to retarget to net7, it's only the runtime that changes. You can keep building with net5/6. Otherwise, yes `WasmShellRuntimeCopyExclude` could be a way to work around it.

**Comment by groogiam** [comment]
I'm getting This error when building with [7.0.0-dev.175](https://www.nuget.org/packages/Uno.Wasm.Bootstrap/7.0.0-dev.175)

`emcc_link.ps1 s not digitally signed. You cannot run this script on the current system.`

**Comment by jeromelaban** [comment]
You'll need to adjust the configuration of your system for that to [allow unsigned scripts execution](https://superuser.com/questions/106360/how-to-enable-execution-of-powershell-scripts).

**Comment by groogiam** [comment]
Thanks. After allowing remote signed it builds but the managed directory is empty.

![image](https://user-images.githubusercontent.com/1992395/193645319-5e46f8b6-3f93-487e-9bd5-b0bf7e640a83.png)

It also seems to be adding the bin and obj files to my project. Is that expected?
This causes typescript errors on subsequent runs.
![image](https://user-images.githubusercontent.com/1992395/193645457-51db25c2-ade6-41b1-bbd7-513d74255767.png)

**Comment by jeromelaban** [comment]
It's likely that you have another issue. [Take a look at the binlogs](https://platform.uno/docs/articles/uno-builds-troubleshooting.html) to determine what's not working.

**Comment by groogiam** [comment]
I was able to get this working in 3.3.x by manually loading the new runtime dll. This worked in this case because System.Net.Quic was not referenced by default.
However now I am still seeing some strange linker behavior.

I'm seeing some strange behavior with the linker on 3.3.x. It seems to be trimming Uno.Foundation when the LinkerConfig.xml has an entry to ignore it. `<assembly fullname="Uno.Foundation" />`. It's probably doing this with other assemblies as well. Is there any way to prevent this? I would use `<WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>`  but this results in some compilation conflict with the sqlite wasm module and SQLitePCLRaw.core. 

![image](https://user-images.githubusercontent.com/1992395/193860112-8e0b0d33-2b47-4d70-8e7d-778603126cc1.png)

**Comment by groogiam** [comment]
Closing as my use case looks like it is better suited for the [.NET wasm-tools workload](https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-7.0).
