### ISSUE TITLE
[Wasm] PWA service-worker.js : SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by igiona** [unoplatform/Uno.Wasm.Bootstrap#659]
### Current behavior

A freshly PWA WASM application created using VS22 template, creates the necessary PWA files, but while executing I get the following error on the browser (chrome 108.0.5359.125 (Official Build) (64-bit) (cohort: Stable)):
```
Uncaught (in promise) SyntaxError: Unexpected token 'export'
    at service-worker.js:11:26
```

As result, the under "installability" the browser reports an error.

![image](https://user-images.githubusercontent.com/1524038/211664980-968b6e19-0206-4bc8-950e-3bd399c7ea96.png)

### Expected behavior

The service-worker is loaded successfully, and the browser can install the application.

### How to reproduce it (as minimally and precisely as possible)

Create a fresh Uno WASM with the PWA option enabled.
Load the published output to a web server and check the Chrome dev-tools.

An example can be found here: https://www.immo-electronics.ch/scewo/figma/

Uno Platform Check v1.10.0.0

### Workaround

The issue seems to come from the "export { config }" line in uno-config.js, which can't be "eval" at runtime within the service-worker.js .

I tried to C&P the "offline_files" list directly into the service-work.js, but I got the following error:
`Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed
`

The same error can be also seen in this Uno based website: https://nuget.info/packages which appears not to have the "export" statement into the uno-config.js.

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

```
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageReference Include="Uno.Toolkit.WinUI.Material" Version="2.4.2" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="4.6.39" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.6.39" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.39" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="7.0.3" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.3" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.6.39" />
```

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.4.3

**Comment by igiona** [comment]
@jeromelaban thanks for the fix, I tried on my end and indeed the caching issue is now gone and the console looks clean.
On the other hand, the issue still persists:
_see https://www.immo-electronics.ch/scewo/figma/_


![image](https://user-images.githubusercontent.com/1524038/212171259-a390ec1d-6c99-4c8d-a168-9ef4b13dd24b.png)

![image](https://user-images.githubusercontent.com/1524038/212171197-d8af7bb9-8b94-45b6-9f31-d33614a4a29f.png)

**Comment by jeromelaban** [comment]
Thanks for trying it out. Indeed, the installation issue is not the same. I wonder if this is related to the "scope" field in your manifest. Could you set it to `./` or  `/scewo/figma/` to see if it helps?

**Comment by igiona** [comment]
I tried to change the scope as you mentioned but it didn't help
I also tried to re-generate the whole distribution package, re-apply your patch, and I now see that I get an interesting output:
`[ServiceWorker] Failed to fetch ./package_9f45c810898ac5da43db5c15897fb12483116170/service-worker.js`
=> https://www.immo-electronics.ch/scewo/figma/

_I guess in my previous playground I did copied the service-worker in the "package_" in one of the many trials to fix the issue_

I then moved the deployment straight to the website root:
=> https://www.immo-electronics.ch/
and it worked! But the 
`[ServiceWorker] Failed to fetch ./package_9f45c810898ac5da43db5c15897fb12483116170/service-worker.js`
is still there

Any idea why the service worker fails if is placed in a sub directory?

**Comment by jeromelaban** [comment]
Thanks for the update. The `service-worker.js` change is part of https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/660,  using the boostrapper `8.0.0-dev.77` or later should make this particular error go away.

Now with regards to the sub path, this means that you may also need [to change this](https://platform.uno/docs/articles/external/uno.wasm.bootstrap/doc/features-deep-linking.html), so that the service worker gets registered at the right location. Still, there may be additional issues there, so let us know if this helps.

**Comment by igiona** [comment]
Hi @jeromelaban, I tried dev-77 and after manually removing the "invalid file" I'm in the same situation:

compiled  without `<WasmShellWebAppBasePath>/scewo/figma/</WasmShellWebAppBasePath>`
works on chrome: https://www.immo-electronics.ch/

compiled with <WasmShellWebAppBasePath>/scewo/figma/</WasmShellWebAppBasePath> 
does not work (same installation error): https://www.immo-electronics.ch/scewo/figma/

compiled with <WasmShellWebAppBasePath>./scewo/figma2/</WasmShellWebAppBasePath> 
does not (app doesn't even load due to 404 on basically all JS) : I also tried https://www.immo-electronics.ch/scewo/figma2/ 

Interestingly, on Firefox none of the above works

**Comment by DierkDroth** [comment]
@jeromelaban I see some console errors as I'm trying to make by app a PWA which I believe are are related:
```
A bad HTTP response code (404) was received when fetching the script.
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('XXX') with script ('XXX/service-worker.js'): ServiceWorker cannot be started
```

Not sure if relevant by I also have this in my project file
`<WasmShellWebAppBasePath>/app/wasm/Latest/</WasmShellWebAppBasePath>`

I'm on Bootstrap 8.0.0-dev.77

**Comment by DierkDroth** [comment]
@jeromelaban I saw some console errors - which I believe they are related - as I'm trying to make my app a PWA:
```
A bad HTTP response code (404) was received when fetching the script.
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('XXX') with script ('XXX/service-worker.js'): ServiceWorker cannot be started
```

Next I updated to latest `Bootstrap 8.0.0-dev.77` (full config in screenshot below) but now am getting the error as per screenshot below right on startup = the app doesn't event start.

Not sure if relevant by I also have this in my project file
`<WasmShellWebAppBasePath>/app/wasm/Latest/</WasmShellWebAppBasePath>`

What am I doing wrong?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/212297230-3861dffa-8ee8-473a-980d-90a92549e8f0.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/212297301-ea5f1300-e984-4994-91e5-de70aff69ae3.png">

**Comment by jeromelaban** [comment]
@igiona @DierkDroth thanks for the update. These are not related to the original issue here, so let's track it in https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/662.
