### ISSUE TITLE
[WASM] Bug in 'service-worker.js' when using the 'WasmPWAManifestFile' option in project file

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/Uno.Wasm.Bootstrap#784]
I'm trying to make my UNO WASM app [a proper PWA](https://platform.uno/docs/articles/external/uno.wasm.bootstrap/doc/features-pwa.html) and added the `WasmPWAManifestFile `option to my project file. 
This appears to create a `./service-worker.js` file -> good.

However, there is a bug in `./service-worker.js` when importing `uno-config.js` by this line:
```
import { config } from "/app/wasm/Latest/package_ad1491e5a8b56662fc53c8e8bb7a424a4d067fbb//uno-config.js";
```

Note the double slashes `...//uno-config.js` which apparently throws off my AWS S3 file hosting, since the browsers returns a 404 error.

**Comment by TopProgrammer77** [comment]
@DierkDroth 
Why do you use '//' instead of '/'?

**Comment by DierkDroth** [comment]
@TopProgrammer77 to be clear: I'm not doing anything AFAIK. That code line is generated by UNO

**Comment by DierkDroth** [comment]
Thanks for merging @jeromelaban. I'll try the fix as a build is available
