### ISSUE TITLE
[8.0.7] Updating from 8.0.4 to latest bootstrap breaks the solution

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/Uno.Wasm.Bootstrap#819]
@jeromelaban when updating to latest bootstrap as per screenshot below I now get this error when building the solution. Same error when cleaning the solution.

```
9>C:\Users\dierk\.nuget\packages\uno.wasm.bootstrap\8.0.7\build\Uno.Wasm.Bootstrap.targets(313,3): error MSB4036: The "RemoveDirTask_vb743e89e9a0a9c81a4f7ed2b35cad4f3c88ee67d" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64" directory.
9>Done building project "Unusual.Wasm.csproj" -- FAILED.
```

Any idea what's going wrong?

<img width="1280" alt="image" src="https://github.com/unoplatform/Uno.Wasm.Bootstrap/assets/26179242/0f9a13ca-c1e2-46b7-b6c8-224996892d96">

<img width="1280" alt="image" src="https://github.com/unoplatform/Uno.Wasm.Bootstrap/assets/26179242/c4790ae0-16d0-4287-996f-f3ac7614dbb7">

**Comment by jeromelaban** [comment]
Thanks for the report. There's a missing target that we'll add soon. You can keep using 8.0.4 in the meantime.

**Comment by DierkDroth** [comment]
@jeromelaban thanks for your quick reply.
