### ISSUE TITLE
<meta name="apple-mobile-web-app-capable" content="yes"> is deprecated.

### ISSUE THREAD

**Issue by guyulmaz** [unoplatform/Uno.Wasm.Bootstrap#881]
```
				// See https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html
				extraBuilder.AppendLine($"<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">");
```

`Login:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">`

**Comment by guyulmaz** [comment]
Hi when this fix will go into dev uno.sdk nuget ?

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/8.0

**Comment by jeromelaban** [comment]
> Hi when this fix will go into dev uno.sdk nuget ?

It will be in a few days, thanks for reporting!
