### ISSUE TITLE
Use package reference to another NetStandard project in AOT mode

### ISSUE THREAD

**Issue by PadreSVK** [unoplatform/Uno.Wasm.Bootstrap#89]
nuget version 1.0.0-dev.269
When I add package reference from bootstraped project to another NetStandard project I get this error message 
`"/mnt/c/Users/patri/Documents/_tests/unobootstrap/WasmAOT/WasmAOT.csproj" (default target) (1:7) ->
"/mnt/c/Users/patri/Documents/_tests/unobootstrap/NetStandardLib/NetStandardLib.csproj" (default target) (2:6) ->
(GenerateBuildDependencyFile target) ->
  /usr/share/dotnet/sdk/2.2.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/mnt/c/Users/patri/Documents/_tests/unobootstrap/NetStandardLib/NetStandardLib.csproj]
/usr/share/dotnet/sdk/2.2.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018: System.TypeLoadException: Could not load type of field 'Microsoft.NET.Build.Tasks.DependencyContextBuilder:_filteredPackages' (12) due
to: Could not resolve type with token 01000027 from typeref (expected class 'NuGet.Packaging.Core.PackageIdentity' in assembly 'NuGet.Packaging, Version=5.0.0.6, Culture=neutral, PublicKeyToken=31bf3856ad364e35') assembly:NuGet.Packaging, Version=5.0.0.6, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:NuGet.Packaging.Core.PackageIdentity member:(null) [/mnt/c/Users/patri/Documents/_tests/unobootstrap/NetStandardLib/NetStandardLib.csproj]
/usr/share/dotnet/sdk/2.2.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <c5e0e1dbe29a4fae9ad829d4b52ccc8b>:0  [/mnt/c/Users/patri/Documents/_tests/unobootstrap/NetStandardLib/NetStandardLib.csproj]
/usr/share/dotnet/sdk/2.2.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <58f0218f988743a48dd7c84cbe933f4e>:0  [/mnt/c/Users/patri/Documents/_tests/unobootstrap/NetStandardLib/NetStandardLib.csproj]
/usr/share/dotnet/sdk/2.2.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x001f6] in <58f0218f988743a48dd7c84cbe933f4e>:0  [/mnt/c/Users/patri/Documents/_tests/unobootstrap/NetStandardLib/NetStandardLib.csproj]`

Iinker
`<linker>
  <assembly fullname="WasmAOT" />
  <assembly fullname="NetStandardLib" />
</linker>`

csproj reference 
`    <ProjectReference Include="..\NetStandardLib\NetStandardLib.csproj">
      <Private>true</Private>
    </ProjectReference>`

**Comment by jeromelaban** [comment]
@PadreSVK this looks like an issue that comes from msbuild itself. Which version of msbuild are you running ?

**Comment by PadreSVK** [comment]
@jeromelaban 
I have msbuild in version 16.0.0.0

**Comment by jeromelaban** [comment]
Aligning mono and .net core versions generally fixes those issues, or using `dotnet build`.
